name       : opensc
version    : 0.22.0
release    : 9
source     :
    - https://github.com/OpenSC/OpenSC/releases/download/0.22.0/opensc-0.22.0.tar.gz : 8d4e5347195ebea332be585df61dcc470331c26969e4b0447c851fb0844c7186
homepage   : https://github.com/OpenSC/OpenSC
license    : LGPL-2.1-or-later
component  : security.library
summary    : OpenSC provides a set of libraries and utilities to work with smart cards
description: |
    OpenSC provides a set of libraries and utilities to work with smart cards. Its main focus is on cards that support cryptographic operations, and facilitate their use in security applications such as authentication, mail encryption and digital signatures. OpenSC implements the standard APIs to smart cards, e.g. PKCS#11 API.
builddeps  :
    - pkgconfig(libpcsclite)
    - docbook-xml
rundeps    :
    - pcsc-lite
setup      : |
    export styledir=(/usr/share/xml/docbook/xsl-stylesheets-*)

    %reconfigure --disable-static \
                 --enable-man \
                 --with-xsl-stylesheetsdir=$styledir
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 etc/opensc.conf "$installdir/etc/opensc.conf"
