name       : opensc
version    : 0.18.0
release    : 2
source     :
    - https://github.com/OpenSC/OpenSC/releases/download/0.18.0/opensc-0.18.0.tar.gz : 9bc0ff030dd1c10f646d54415eae1bb2b1c72dda710378343f027e17cd8c3757
license    : LGPL-2.1-or-later
component  : security.library
summary    : OpenSC provides a set of libraries and utilities to work with smart cards
description: |
    OpenSC provides a set of libraries and utilities to work with smart cards.
    Its main focus is on cards that support cryptographic operations, and
    facilitate their use in security applications such as authentication, mail
    encryption and digital signatures. OpenSC implements the standard APIs to
    smart cards, e.g. PKCS#11 API.
builddeps  :
    - pkgconfig(libpcsclite)
    - docbook-xml
rundeps    :
    - pcsc-lite
setup      : |
    %patch -p1 < $pkgfiles/opensc-bash-completion.patch
    export styledir=(/usr/share/xml/docbook/xsl-stylesheets-*)

    %reconfigure --disable-static \
                 --enable-man \
                 --with-xsl-stylesheetsdir=$styledir
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 etc/opensc.conf "$installdir/etc/opensc.conf"
