name       : opensc
version    : 0.17.0
release    : 1
source     :
    - https://github.com/OpenSC/OpenSC/releases/download/0.17.0/opensc-0.17.0.tar.gz : be73c6816867ab4721e6a9ae7dba8e890c5f169f0a2cbb4bf354e0f30a948300
license    : LGPL-2.1
component  : security.library
summary    : OpenSC provides a set of libraries and utilities to work with smart cards
description: |
    OpenSC provides a set of libraries and utilities to work with smart cards.
    Its main focus is on cards that support cryptographic operations, and
    facilitate their use in security applications such as authentication, mail
    encryption and digital signatures. OpenSC implements the standard APIs to
    smart cards, e.g. PKCS#11 API.
builddeps  :
    - pkgconfig(libpcsclite)
    - docbook-xml
rundeps    :
    - pcsc-lite
setup      : |
    %patch -p1 < $pkgfiles/opensc-bash-completion.patch
    %patch -p1 < $pkgfiles/opensc-coolkey.patch
    %patch -p1 < $pkgfiles/add-ecc-and-solve-status-codes-length-with-sm-card.patch
    export styledir=(/usr/share/xml/docbook/xsl-stylesheets-*)

    %reconfigure --disable-static \
                 --enable-man \
                 --with-xsl-stylesheetsdir=$styledir
build      : |
    %make
install    : |
    %make_install
    install -D -m644 etc/opensc.conf "$installdir/etc/opensc.conf"
